#runtime: python27
#api_version: 1
#threadsafe: true

#handlers:
#- url: /static
#  static_dir: static
#- url: /.*
#  script: app.app
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
        python_version: 3
env_variables:
        CLOUD_STORAGE_BUCKET: cs410c-taisheng
